var Sem1JsonValue =
    [
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "Developmental Counselling",
    "specialisationCode": "DC",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Digital Photography",
        "code": "MG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "MG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Voice Culture and Modulation",
        "code": "MG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "MG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fashion Craft",
        "code": "TG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "TG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Fashion",
        "code": "TG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "TG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Development and Guidance During Early Years",
        "code": "HCI03",
        "isElective": "No",
        "order": "7",
        "paperCode": "HCI03",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    }
    ]
},
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "Early Childhood Care And Education",
    "specialisationCode": "ECCE",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Digital Photography",
        "code": "MG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "MG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Voice Culture and Modulation",
        "code": "MG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "MG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fashion Craft",
        "code": "TG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "TG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Fashion",
        "code": "TG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "TG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Development and Guidance During Early Years",
        "code": "HCI03",
        "isElective": "No",
        "order": "7",
        "paperCode": "HCI03",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    }
    ]
},
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "Food Nutrition And Dietetics",
    "specialisationCode": "FND",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Consumer Education and Financial Literacy",
        "code": "RG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "RG101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Travel Arrangements and Formalities",
        "code": "RG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "RG102",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Personal and Professional Relationships in Adulthood",
        "code": "HG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "HG101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Marriage and Parenting",
        "code": "HG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "HG102",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""

    },
    {
        "paperTitle": "Fundamentals of Nutrition",
        "code": "FCI03",
        "isElective": "No",
        "order": "5",
        "paperCode": "FCI03",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Nutrition",
        "code": "FCI03P",
        "isElective": "No",
        "order": "5",
        "paperCode": "FCI03P",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "0",
        "theoryExternalSection2Max": "100",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "2",
        "maxGrace": ""
    }
    ]
},
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "HOSPITALITY & TOURISM MANAGEMENT",
    "specialisationCode": "HTM",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {

        "paperTitle": "Nutrition for Health Promotion",
        "code": "FG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "FG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Baking",
        "code": "FG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "FG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fashion Craft",
        "code": "TG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "TG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Fashion",
        "code": "TG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "TG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Personal Finance and Consumer Studies",
        "code": "RCI03",
        "isElective": "No",
        "order": "7",
        "paperCode": "RCI03",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    }
    ]
},
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "Interior Design And Resource Management",
    "specialisationCode": "IDRM",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {

        "paperTitle": "Nutrition for Health Promotion",
        "code": "FG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "FG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Baking",
        "code": "FG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "FG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fashion Craft",
        "code": "TG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "TG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Fashion",
        "code": "TG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "TG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Personal Finance and Consumer Studies",
        "code": "RCI03",
        "isElective": "No",
        "order": "7",
        "paperCode": "RCI03",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    }
    ]
},
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "Mass Communication And Extension",
    "specialisationCode": "MCE",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Nutrition for Health Promotion",
        "code": "FG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "FG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Baking",
        "code": "FG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "FG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fashion Craft",
        "code": "TG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "TG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Fashion",
        "code": "TG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "TG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Communication",
        "code": "MCI03",
        "isElective": "No",
        "order": "7",
        "paperCode": "MCI03",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "0",
        "theoryExternalSection2Max": "100",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    }
    ]
},
{
    "courseName": "Bachelor in Science Home Science",
    "courseShortName": "BSc - Regular",
    "marksheetName": "",
    "specialisation": "Textiles And Apparel Designing",
    "specialisationCode": "TAD",
    "paperDetails": [
    {
        "paperTitle": "Communicative English",
        "code": "LA101",
        "isElective": "No",
        "order": "1",
        "paperCode": "LA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Environmental Studies",
        "code": "SA101",
        "isElective": "No",
        "order": "2",
        "paperCode": "SA101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Digital Photography",
        "code": "MG101",
        "isElective": "Yes",
        "order": "3",
        "paperCode": "MG101",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Voice Culture and Modulation",
        "code": "MG102",
        "isElective": "Yes",
        "order": "4",
        "paperCode": "MG102",
        "isGrade": "No",
        "isContinousAssessment": true,
        "paperType": "Practical",
        "theoryInternalMax": "0",
        "theoryInternalPassing": "0",
        "theoryExternalSection1Max": "50",
        "theoryExternalSection2Max": "50",
        "theoryExternalPassing": "40",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Personal and Professional Relationships in Adulthood",
        "code": "HG101",
        "isElective": "Yes",
        "order": "5",
        "paperCode": "HG101",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Marriage and Parenting",
        "code": "HG102",
        "isElective": "Yes",
        "order": "6",
        "paperCode": "HG102",
        "isGrade": "No",
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    },
    {
        "paperTitle": "Fundamentals of Textile and Clothing",
        "code": "TCI03",
        "isElective": "No",
        "order": "7",
        "paperCode": "TCI03",
        "isGrade": "No",
        "isContinousAssessment": false,
        "paperType": "Theory",
        "theoryInternalMax": "50",
        "theoryInternalPassing": "20",
        "theoryExternalSection1Max": "25",
        "theoryExternalSection2Max": "25",
        "theoryExternalPassing": "20",
        "practicalMaxMarks": "0",
        "credits": "4",
        "maxGrace": ""
    }
    ]
}
    ]


var Sem1ExamDetailJson = [{
    "paperTitle": "Art, Design and Aesthetics",
    "paperCode": "RCII04",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Travel Management",
    "paperCode": "RCII05",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Nutrition",
    "paperCode": "FCI03P",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "100",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Textile and Clothing",
    "paperCode": "TCI03",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Nutrition",
    "paperCode": "FCI03",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Advanced English",
    "paperCode": "LG102",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Development and Guidance During Early Years",
    "paperCode": "HCI03",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Functional English",
    "paperCode": "LG101",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Science for Life",
    "paperCode": "SG101",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Personal and Professional Relationships in Adulthood",
    "paperCode": "HG101",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Marriage and Parenting",
    "paperCode": "HG102",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Digital Photography",
    "paperCode": "MG101",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "50",
    "theoryExternalSection2Max": "50",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Voice Culture and Modulation",
    "paperCode": "MG102",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "50",
    "theoryExternalSection2Max": "50",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Voice Culture and Modulation",
    "paperCode": "MG104",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Drawing and Designing Techniques",
    "paperCode": "RCII24",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Communicative English",
    "paperCode": "LA101",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Digital Photography",
    "paperCode": "MG103",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Human Anatomy and Physiology",
    "paperCode": "FCII06",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Nutrition across the Life Cycle",
    "paperCode": "FCII05",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Fashion",
    "paperCode": "TG102",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fashion Craft",
    "paperCode": "TG101",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "50",
    "theoryExternalSection2Max": "50",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Development and Guidance During School Years",
    "paperCode": "HCII04",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Environmental Studies",
    "paperCode": "SA101",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Parenting During Childhood Years",
    "paperCode": "HCII05",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Methods and Materials for Teaching Children",
    "paperCode": "HCII06",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Consumer Education and Financial Literacy",
    "paperCode": "RG101",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Travel Arrangements and Formalities",
    "paperCode": "RG102",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Nutrition for Health Promotion",
    "paperCode": "FG101",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Theory",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "50",
    "theoryExternalSection2Max": "50",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Bakery",
    "paperCode": "FG102",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Theory",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "50",
    "theoryExternalSection2Max": "50",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Fashion and Retail",
    "paperCode": "TCII04",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Customer Relationship Management",
    "paperCode": "RCV22",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Fashion Illustration",
    "paperCode": "TCII06",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Clothing",
    "paperCode": "TCII05",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Contemporary Social Issues",
    "paperCode": "MCII04",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Personal Finance and Consumer Studies",
    "paperCode": "RCI03",
    "isGrade": "No",
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Photography",
    "paperCode": "MCII05",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Ergonomics",
    "paperCode": "RCIII07",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Management of Resources",
    "paperCode": "RCIII06",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Ergonomics",
    "paperCode": "RCIII08",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
}, {
    "paperTitle": "House Keeping and Facility management",
    "paperCode": "RCIII09",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "House Keeping and Facility management",
    "paperCode": "RCIII10",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
}, {
    "paperTitle": "Residential Interior Design",
    "paperCode": "RCIII27",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
}, {
    "paperTitle": "Residential Architecture",
    "paperCode": "RCIII26",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Residential Architecture",
    "paperCode": "RCIII25",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Indian Tourism",
    "paperCode": "RCIII11",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
},
{
    "paperTitle": "Fundamentals of Communication",
    "paperCode": "MCI03",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "100",
    "theoryExternalPassing": "40",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Basic Building Services",
    "paperCode": "RCIII28",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Rendering and Presentation",
    "paperCode": "RCIII37",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Basic Dietics",
    "paperCode": "FCIII07",
    "isGrade": "No",
    "isContinousAssessment": true,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Basic Dietics",
    "paperCode": "FCIII08",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "0",
    "theoryInternalPassing": "0",
    "theoryExternalSection1Max": "0",
    "theoryExternalSection2Max": "0",
    "theoryExternalPassing": "0",
    "practicalMaxMarks": "100",
    "credits": "2",
    "maxGrace": ""
}, {
    "paperTitle": "Nutritional Biochemistry",
    "paperCode": "FCIII10",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Nutritional Biochemistry",
    "paperCode": "FCIII09",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Food Science",
    "paperCode": "FCIII12",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Practical",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "2",
    "maxGrace": ""
},
{
    "paperTitle": "Food Science",
    "paperCode": "FCIII11",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}, {
    "paperTitle": "Hospital Food Service Management",
    "paperCode": "FCIII24",
    "isGrade": "No",
    "isContinousAssessment": false,
    "paperType": "Theory",
    "theoryInternalMax": "50",
    "theoryInternalPassing": "20",
    "theoryExternalSection1Max": "25",
    "theoryExternalSection2Max": "25",
    "theoryExternalPassing": "20",
    "practicalMaxMarks": "0",
    "credits": "4",
    "maxGrace": ""
}
]


var Sem1GeneralElectiveInfo = [
    {
        'Specialization': 'HOSPITALITY & TOURISM MANAGEMENT',
        "specialisationCode": "HTM",
        'ElectiveSubject': [
          {
              'Title': 'TG GE',
              'Subject': [{
                  'Code': 'TG102'
              }, {
                  'Code': 'TG101'
              }]
          },
        {
            'Title': 'FG GE',
            'Subject': [
              {
                  'Code': 'FG101'
              }, {
                  'Code': 'FG102'
              }]
        }
        ]
    },
    {
        'Specialization': 'Food Nutrition And Dietetics',
        "specialisationCode": "FND",
        'ElectiveSubject': [
          {
              'Title': 'HD GE',
              'Subject': [{
                  'Code': 'HG101'
              }, {
                  'Code': 'HG102'
              }]
          },
        {
            'Title': 'RM GE',
            'Subject': [
              {
                  'Code': 'RG101'
              }, {
                  'Code': 'RG102'
              }]
        }
        ]
    },
    {
        'Specialization': 'Developmental Counselling',
        "specialisationCode": "DC",
        'ElectiveSubject': [
          {
              'Title': 'TAD GE',
              'Subject': [{
                  'Code': 'TG101'
              }, {
                  'Code': 'TG102'
              }]
          },
        {
            'Title': 'MCE GE',
            'Subject': [
              {
                  'Code': 'MG101'
              }, {
                  'Code': 'MG102'
              }]
        }
        ]
    },
    {
        'Specialization': 'Mass Communication And Extension',
        "specialisationCode": "MCE",
        'ElectiveSubject': [
          {
              'Title': 'TAD GE',
              'Subject': [{
                  'Code': 'TG101'
              }, {
                  'Code': 'TG102'
              }]
          },
            {
                'Title': 'FSN GE',
                'Subject': [
                  {
                      'Code': 'FG101'
                  }, {
                      'Code': 'FG102'
                  }]
            }
        ]
    },
    {
        'Specialization': 'Textiles And Apparel Designing',
        "specialisationCode": "TAD",
        'ElectiveSubject': [
          {
              'Title': 'HD GE',
              'Subject': [{
                  'Code': 'HG101'
              }, {
                  'Code': 'HG102'
              }]
          },
            {
                'Title': 'MCE GE',
                'Subject': [
                  {
                      'Code': 'MG101'
                  }, {
                      'Code': 'MG102'
                  }]
            }
        ]
    }, {
        'Specialization': 'Early Childhood Care And Education',
        "specialisationCode": "ECCE",
        'ElectiveSubject': [
          {
              'Title': 'TAD GE',
              'Subject': [{
                  'Code': 'TG101'
              }, {
                  'Code': 'TG102'
              }]
          },
        {
            'Title': 'MCE GE',
            'Subject': [
              {
                  'Code': 'MG101'
              }, {
                  'Code': 'MG102'
              }]
        }
        ]
    }
]
