//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhaariAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouriteJob
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string JobSource { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string DatePosted { get; set; }
        public System.DateTime DateFavorited { get; set; }
        public string JobId { get; set; }
    }
}
