-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 19:53:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema attendande_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema attendande_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendande_tracker` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `attendande_tracker` ;

-- -----------------------------------------------------
-- Table `attendande_tracker`.`library_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendande_tracker`.`library_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_card_number` VARCHAR(200) NOT NULL,
  `crn` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL,
  `in_time` DATETIME NOT NULL,
  `out_time` DATETIME NULL,
  `pushed` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `id_card_number_IDX` (`id_card_number` ASC),
  INDEX `library_log_date_IDX` (`date` ASC),
  INDEX `library_log_in_time_IDX` (`in_time` ASC),
  INDEX `library_log_crn_IDX` (`crn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendande_tracker`.`staff_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendande_tracker`.`staff_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `crn` INT(11) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `employee_code` VARCHAR(100) NULL,
  `department` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `crn_UNIQUE` (`crn` ASC),
  UNIQUE INDEX `employee_code_UNIQUE` (`employee_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendande_tracker`.`student_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendande_tracker`.`student_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `crn` VARCHAR(150) NOT NULL,
  `library_card_no` VARCHAR(200) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `course_details_year` VARCHAR(80) NULL,
  `course_details_course_name` VARCHAR(400) NULL,
  `course_name` VARCHAR(100) NOT NULL,
  `specialization` VARCHAR(255) NOT NULL,
  `roll_number` INT(100) NULL,
  `division` VARCHAR(100) NULL,
  `prn_number` VARCHAR(50) NULL,
  `photo_path` VARCHAR(200) NULL,
  `admission_year` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `crn_UNIQUE` (`crn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendande_tracker`.`synchronizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendande_tracker`.`synchronizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `synced_at` DATETIME NOT NULL,
  `sync_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sync_type_IDX` (`sync_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendande_tracker`.`course_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendande_tracker`.`course_details` (
  `id` INT(100) NOT NULL,
  `year` VARCHAR(80) NULL,
  `course_name` VARCHAR(400) NULL,
  `course_type` VARCHAR(200) NULL,
  `specialization` VARCHAR(400) NULL,
  `short_form` VARCHAR(120) NULL,
  `status` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
