//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerOffer
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string OfferName { get; set; }
        public string OfferType { get; set; }
        public string OfferText { get; set; }
        public System.DateTime OfferStartDate { get; set; }
        public System.DateTime OfferEndDate { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModfied { get; set; }
        public System.DateTime DateActivation { get; set; }
        public System.DateTime DateExpiry { get; set; }
        public string offerImage { get; set; }
    
        public virtual PartnerDetail PartnerDetail { get; set; }
    }
}
