//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerLocationWorkTime
    {
        public int ID { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string WorkDay { get; set; }
        public string WorkStartTime { get; set; }
        public string WorkEndTime { get; set; }
        public string Status { get; set; }
    
        public virtual PartnerDetail PartnerDetail { get; set; }
        public virtual PartnerLocationDetail PartnerLocationDetail { get; set; }
        public virtual PartnerLocationWorkTime PartnerLocationWorkTime1 { get; set; }
        public virtual PartnerLocationWorkTime PartnerLocationWorkTime2 { get; set; }
    }
}
