//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerLocationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerLocationDetail()
        {
            this.PartnerLocationWorkTimes = new HashSet<PartnerLocationWorkTime>();
        }
    
        public int ID { get; set; }
        public int PartnerId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public System.DateTime DateActivated { get; set; }
        public System.DateTime DateExpiry { get; set; }
        public string Status { get; set; }
        public string IFSCCode { get; set; }
    
        public virtual PartnerDetail PartnerDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerLocationWorkTime> PartnerLocationWorkTimes { get; set; }
    }
}
