//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerCharge
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Frequency { get; set; }
        public string Category { get; set; }
        public double Charges { get; set; }
        public bool IsDefault { get; set; }
        public string Status { get; set; }
    
        public virtual PartnerDetail PartnerDetail { get; set; }
    }
}
