//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerDetail()
        {
            this.PartnerLocationDetails = new HashSet<PartnerLocationDetail>();
            this.PartnerLocationWorkTimes = new HashSet<PartnerLocationWorkTime>();
            this.PartnerOffers = new HashSet<PartnerOffer>();
            this.PartnerRates = new HashSet<PartnerRate>();
            this.PartnerCharges = new HashSet<PartnerCharge>();
        }
    
        public int ID { get; set; }
        public int UserId { get; set; }
        public string PartnerName { get; set; }
        public string PartnerLogoPath { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public string Status { get; set; }
        public string RedirectLink { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerLocationDetail> PartnerLocationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerLocationWorkTime> PartnerLocationWorkTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerOffer> PartnerOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRate> PartnerRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerCharge> PartnerCharges { get; set; }
    }
}
