//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParam
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Key { get; set; }
        public string DisplayValue { get; set; }
        public string Value { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
    }
}
