//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReminder
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string RateCondition { get; set; }
        public double Rate { get; set; }
        public double Distance { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
