//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRewardPoint
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string TransactionId { get; set; }
        public string RewardPointsEarned { get; set; }
        public System.DateTime DateEarned { get; set; }
        public string Comments { get; set; }
    }
}
