//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string NotificationText { get; set; }
        public string NotificationType { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateRead { get; set; }
        public string Status { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
