//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigettr.Services.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.ISurveyUserManagmentApi")]
    public interface ISurveyUserManagmentApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/InsertSurvey", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/InsertSurveyResponse")]
        string InsertSurvey(string Templatename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/InsertSurvey", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/InsertSurveyResponse")]
        System.Threading.Tasks.Task<string> InsertSurveyAsync(string Templatename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/InsertUser", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/InsertUserResponse")]
        int InsertUser(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/InsertUser", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/InsertUserResponse")]
        System.Threading.Tasks.Task<int> InsertUserAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/UpdateSyrvey", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/UpdateSyrveyResponse")]
        int UpdateSyrvey(string SurveyID, string Templatename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/UpdateSyrvey", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/UpdateSyrveyResponse")]
        System.Threading.Tasks.Task<int> UpdateSyrveyAsync(string SurveyID, string Templatename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/Getsharelinks", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/GetsharelinksResponse")]
        string Getsharelinks(string Surveyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyUserManagmentApi/Getsharelinks", ReplyAction="http://tempuri.org/ISurveyUserManagmentApi/GetsharelinksResponse")]
        System.Threading.Tasks.Task<string> GetsharelinksAsync(string Surveyid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISurveyUserManagmentApiChannel : Navigettr.Services.ServiceReference3.ISurveyUserManagmentApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SurveyUserManagmentApiClient : System.ServiceModel.ClientBase<Navigettr.Services.ServiceReference3.ISurveyUserManagmentApi>, Navigettr.Services.ServiceReference3.ISurveyUserManagmentApi {
        
        public SurveyUserManagmentApiClient() {
        }
        
        public SurveyUserManagmentApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SurveyUserManagmentApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyUserManagmentApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyUserManagmentApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertSurvey(string Templatename) {
            return base.Channel.InsertSurvey(Templatename);
        }
        
        public System.Threading.Tasks.Task<string> InsertSurveyAsync(string Templatename) {
            return base.Channel.InsertSurveyAsync(Templatename);
        }
        
        public int InsertUser(string Username) {
            return base.Channel.InsertUser(Username);
        }
        
        public System.Threading.Tasks.Task<int> InsertUserAsync(string Username) {
            return base.Channel.InsertUserAsync(Username);
        }
        
        public int UpdateSyrvey(string SurveyID, string Templatename) {
            return base.Channel.UpdateSyrvey(SurveyID, Templatename);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSyrveyAsync(string SurveyID, string Templatename) {
            return base.Channel.UpdateSyrveyAsync(SurveyID, Templatename);
        }
        
        public string Getsharelinks(string Surveyid) {
            return base.Channel.Getsharelinks(Surveyid);
        }
        
        public System.Threading.Tasks.Task<string> GetsharelinksAsync(string Surveyid) {
            return base.Channel.GetsharelinksAsync(Surveyid);
        }
    }
}
